# Generated by Django 2.1.7 on 2019-09-12 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(max_length=255, null=True, verbose_name='Краткое описание категории для главной'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 11, 56, 37, 133655), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
