# Generated by Django 2.2.4 on 2019-09-30 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190912_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 30, 12, 7, 23, 910711), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
