# Generated by Django 2.2.4 on 2019-08-04 22:58

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20190804_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='category',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material',
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='f_id',
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка на все товары в подкатегории %'),
        ),
        migrations.AddField(
            model_name='filter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='Подкатегория'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.Category', verbose_name='В категории'),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание подкатегории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_img/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 22, 58, 55, 632468), verbose_name='Срок действия безлимитного кода'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
