# Generated by Django 2.2.4 on 2019-08-04 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190804_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 4, 23, 19, 59, 20774), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
