# Generated by Django 2.2.7 on 2020-03-05 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20190930_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 11, 20, 46, 312443), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
