# Generated by Django 2.2.4 on 2019-08-05 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20190804_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='image_small',
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='items/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 5, 19, 59, 11, 689136), verbose_name='Срок действия безлимитного кода'),
        ),
    ]
