# Generated by Django 2.2.4 on 2019-09-23 21:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='badgeColor',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет бейджа'),
        ),
        migrations.AddField(
            model_name='banner',
            name='badgeTextColor',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет текста в бейдже'),
        ),
        migrations.AddField(
            model_name='banner',
            name='bigTextColor',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет текста заголовка'),
        ),
        migrations.AddField(
            model_name='banner',
            name='buttonColor',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет кнопки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='smallTextColor',
            field=colorfield.fields.ColorField(default='#000000', max_length=18, verbose_name='Цвет текста описания'),
        ),
    ]
