# Generated by Django 2.2.7 on 2020-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_banner_buttontextcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Почта')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='Сообщение')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
            },
        ),
    ]
