# Generated by Django 2.2.4 on 2019-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Надпись'),
        ),
    ]
