# Generated by Django 2.2.4 on 2019-09-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_itemtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtext',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='В заказе'),
        ),
    ]
