# Generated by Django 2.2.4 on 2019-09-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190930_1622'),
        ('order', '0003_auto_20190930_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemText',
        ),
    ]
