# Generated by Django 2.2.4 on 2019-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delete_itemtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsinorder',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Надпись'),
        ),
    ]
